import type { Brand } from "../../../util/brand.type.js";
import { faker } from "@faker-js/faker";

export type SimCloudFrontDistributionId = Brand<
  string,
  "SimCloudFrontDistributionId"
>;

/**
 * Simulated CloudFront Distribution.
 */
export class SimCloudFrontDistribution {
  public readonly distributionId: SimCloudFrontDistributionId;

  constructor() {
    // TODO: would it be better if the distribution ID was generated by
    // the CloudFront Registry to guarantee uniqueness ?
    this.distributionId = makeSimCloudFrontDistributionId();
  }
}

function makeSimCloudFrontDistributionId(): SimCloudFrontDistributionId {
  return faker.helpers.fromRegExp(
    // eslint-disable-next-line unicorn/better-regex -- fromRegExp needs 0-9 not \d
    /E[0-9A-Z]{13}/,
  ) as SimCloudFrontDistributionId;
}
