export type {
  SimAthenaAclConfigurationInput,
  SimAthenaDescribedWorkGroup,
  SimAthenaEncryptionConfigurationInput,
  SimAthenaEngineVersionInput,
  SimAthenaListedWorkGroup,
  SimAthenaResultConfigurationInput,
  SimAthenaResultConfigurationUpdatesInput,
  SimAthenaWorkGroupConfigurationInput,
  SimAthenaWorkGroupConfigurationUpdatesInput,
  SimCreateWorkGroupCommand,
  SimCreateWorkGroupCommandInput,
  SimCreateWorkGroupCommandOutput,
  SimDeleteWorkGroupCommand,
  SimDeleteWorkGroupCommandInput,
  SimDeleteWorkGroupCommandOutput,
  SimGetWorkGroupCommand,
  SimGetWorkGroupCommandInput,
  SimGetWorkGroupCommandOutput,
  SimListWorkGroupsCommand,
  SimListWorkGroupsCommandInput,
  SimListWorkGroupsCommandOutput,
  SimUpdateWorkGroupCommand,
  SimUpdateWorkGroupCommandInput,
  SimUpdateWorkGroupCommandOutput,
} from "./work-group/work-group.command.js";
export type {
  SimAthenaDescribedNamedQuery,
  SimAthenaUnprocessedNamedQueryId,
  SimBatchGetNamedQueryCommand,
  SimBatchGetNamedQueryCommandInput,
  SimBatchGetNamedQueryCommandOutput,
  SimCreateNamedQueryCommand,
  SimCreateNamedQueryCommandInput,
  SimCreateNamedQueryCommandOutput,
  SimDeleteNamedQueryCommand,
  SimDeleteNamedQueryCommandInput,
  SimDeleteNamedQueryCommandOutput,
  SimGetNamedQueryCommand,
  SimGetNamedQueryCommandInput,
  SimGetNamedQueryCommandOutput,
  SimListNamedQueriesCommand,
  SimListNamedQueriesCommandInput,
  SimListNamedQueriesCommandOutput,
} from "./named-query/named-query.command.js";
