/**
 * The sim SES v2 Command types, gathered for the service facade.
 */
export type {
  SimCreateEmailIdentityCommand,
  SimCreateEmailIdentityCommandInput,
  SimCreateEmailIdentityCommandOutput,
  SimDeleteEmailIdentityCommand,
  SimDeleteEmailIdentityCommandInput,
  SimDeleteEmailIdentityCommandOutput,
  SimGetEmailIdentityCommand,
  SimGetEmailIdentityCommandInput,
  SimGetEmailIdentityCommandOutput,
  SimListEmailIdentitiesCommand,
  SimListEmailIdentitiesCommandInput,
  SimListEmailIdentitiesCommandOutput,
  SimSesDkimAttributes,
  SimSesDkimSigningAttributes,
  SimSesDkimStatusValue,
  SimSesIdentityInfo,
  SimSesMailFromAttributes,
  SimSesTag,
  SimSesTagInput,
  SimSesVerificationStatusValue,
} from "./identity/identity.command.js";
export type {
  SimSendEmailCommand,
  SimSendEmailCommandInput,
  SimSendEmailCommandOutput,
  SimSesBody,
  SimSesContent,
  SimSesDestination,
  SimSesEmailContent,
  SimSesMessage,
  SimSesRawMessage,
  SimSesTemplate,
} from "./send/send.command.js";
export type {
  SimGetAccountCommand,
  SimGetAccountCommandOutput,
  SimPutAccountDetailsCommand,
  SimPutAccountDetailsCommandInput,
  SimPutAccountDetailsCommandOutput,
  SimPutAccountSuppressionAttributesCommand,
  SimPutAccountSuppressionAttributesCommandInput,
  SimPutAccountSuppressionAttributesCommandOutput,
  SimSesAccountDetailsOutput,
  SimSesSendQuotaDetail,
  SimSesSuppressionAttributes,
} from "./account/account.command.js";
export type {
  SimDeleteSuppressedDestinationCommand,
  SimDeleteSuppressedDestinationCommandInput,
  SimDeleteSuppressedDestinationCommandOutput,
  SimGetSuppressedDestinationCommand,
  SimGetSuppressedDestinationCommandInput,
  SimGetSuppressedDestinationCommandOutput,
  SimListSuppressedDestinationsCommand,
  SimListSuppressedDestinationsCommandInput,
  SimListSuppressedDestinationsCommandOutput,
  SimPutSuppressedDestinationCommand,
  SimPutSuppressedDestinationCommandInput,
  SimPutSuppressedDestinationCommandOutput,
  SimSesSuppressedDestinationDetail,
  SimSesSuppressedDestinationSummary,
} from "./suppression/suppression.command.js";
export type {
  SimCreateEmailTemplateCommand,
  SimCreateEmailTemplateCommandInput,
  SimCreateEmailTemplateCommandOutput,
  SimDeleteEmailTemplateCommand,
  SimDeleteEmailTemplateCommandInput,
  SimDeleteEmailTemplateCommandOutput,
  SimGetEmailTemplateCommand,
  SimGetEmailTemplateCommandInput,
  SimGetEmailTemplateCommandOutput,
  SimListEmailTemplatesCommand,
  SimListEmailTemplatesCommandInput,
  SimListEmailTemplatesCommandOutput,
  SimSesEmailTemplateContent,
  SimSesTemplateMetadata,
  SimUpdateEmailTemplateCommand,
  SimUpdateEmailTemplateCommandInput,
  SimUpdateEmailTemplateCommandOutput,
} from "./template/template.command.js";
